# Generated by Django 6.0.2 on 2026-08-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0024_pilot_feedback'),
        ('users', '0007_consolidar_establecimientos_duplicados'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistant',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='aicase',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='aiquery',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='aiknowledgebase',
            name='nivel',
            field=models.CharField(choices=[('institucional', 'Institucional (solo este colegio)'), ('congregacional', 'Congregacional (toda la Red LiderA+)'), ('nacional', 'Nacional (normativa pública)')], default='institucional', max_length=20, verbose_name='Nivel de acceso'),
        ),
    ]
