# Generated by Django 6.0.2 on 2026-08-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0025_aiassistant_organizacion_aicase_organizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiknowledgebase',
            name='nivel',
            field=models.CharField(choices=[('institucional', 'Institucional (solo este colegio)'), ('organizacional', 'Organizacional (toda la red del cliente)'), ('nacional', 'Nacional (normativa pública)')], default='institucional', max_length=20, verbose_name='Nivel de acceso'),
        ),
    ]
