# Generated by Django 6.0.2 on 2026-08-08 19:42

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0026_alter_aiknowledgebase_nivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiassistant',
            options={'base_manager_name': 'todos'},
        ),
        migrations.AlterModelManagers(
            name='aiassistant',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='aicase',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='aiquery',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='chatconversation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='aiassistant',
            name='motor',
            field=models.CharField(choices=[('v3', 'v3 — dos etapas con citas verificadas (recomendado)'), ('v2', 'v2 — prompt por rol + protocolos por palabra clave'), ('v1', 'v1 — RAG directo con postfiltrado de citas')], default='v3', max_length=2, verbose_name='Motor de respuesta'),
        ),
    ]
