# Generated by Django 6.0.2 on 2026-08-08 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_tenant_multitenancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150)),
                ('rbd', models.CharField(blank=True, max_length=10, verbose_name='RBD')),
                ('es_equipo_central', models.BooleanField(default=False, help_text='Cuota de reuniones ilimitada y visión transversal de la organización.', verbose_name='Equipo central / RED')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['organizacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador (URL)')),
                ('nombre', models.CharField(max_length=150)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('REPRESENTANTE', 'Representante Legal'), ('UTP', 'Unidad Técnica Pedagógica'), ('DIRECTOR', 'Director/a'), ('INSPECTOR', 'Inspector/a General'), ('CONVIVENCIA', 'Coordinador/a de Convivencia Educativa'), ('RED', 'Equipo Red')], default='DIRECTOR', max_length=20, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='user',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='users.establecimiento', verbose_name='Establecimiento (nuevo)'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='users.organizacion'),
        ),
        migrations.AddField(
            model_name='user',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AlterUniqueTogether(
            name='establecimiento',
            unique_together={('organizacion', 'codigo')},
        ),
    ]
