# Generated by Django 6.0.2 on 2026-08-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rellenar_organizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='establishment',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Establecimiento (código)'),
        ),
    ]
