# Generated by Django 6.0.2 on 2026-08-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Organización (slug)'),
        ),
    ]
