# Generated by Django 6.0.2 on 2026-08-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='modulos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de códigos. Vacío = todos, para no romper a quien ya estaba.', verbose_name='Módulos contratados'),
        ),
    ]
