# Generated by Django 6.0.2 on 2026-08-08 19:43

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_eventocultural_organizacion'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventocultural',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
    ]
