# Generated by Django 6.0.2 on 2026-08-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvement_cycle', '0009_add_action_traceability'),
        ('users', '0007_consolidar_establecimientos_duplicados'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementgoal',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='improvementgoal',
            name='profile_role',
            field=models.CharField(blank=True, choices=[('REPRESENTANTE', 'Representante Legal'), ('UTP', 'Unidad Técnica Pedagógica'), ('DIRECTOR', 'Director/a'), ('INSPECTOR', 'Inspector/a General'), ('CONVIVENCIA', 'Coordinador/a de Convivencia Educativa'), ('RED', 'Equipo Red')], max_length=20, verbose_name='Rol responsable'),
        ),
    ]
