# Generated by Django 6.0.2 on 2026-08-08 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvement_cycle', '0010_improvementgoal_organizacion_and_more'),
        ('users', '0008_rellenar_organizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskalert',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organizacion', verbose_name='Organización'),
        ),
    ]
