# Generated by Django 6.0.2 on 2026-08-08 19:43

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('improvement_cycle', '0012_alter_improvementgoal_establishment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='improvementgoal',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='riskalert',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
    ]
