# Generated by Django 6.0.2 on 2026-08-08 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simce', '0005_nueva_arquitectura'),
        ('users', '0007_consolidar_establecimientos_duplicados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesionestudiante',
            options={'ordering': ['-iniciada_en'], 'verbose_name': 'Sesión estudiante'},
        ),
        migrations.AddField(
            model_name='prueba',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='simcedocumento',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='textobiblioteca',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='justificacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='alternativa_correcta',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='enunciado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='habilidad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='habilidad_justificacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐ Inicial'), (2, '⭐⭐ Intermedio'), (3, '⭐⭐⭐ Avanzado')]),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='nivel_justificacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='pista_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='pista_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='prueba_texto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='simce.pruebatexto'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='anio',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_simce', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='rubrica_log',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='rubrica_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='respuestaestudiante',
            name='intentos',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='respuestaestudiante',
            name='puntaje_obtenido',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sesionestudiante',
            name='establecimiento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sesionestudiante',
            name='modo',
            field=models.CharField(choices=[('simce', 'Estilo SIMCE (1 pt, sin pistas)'), ('pistas', 'Con pistas e intentos (4-3-2-0)')], default='simce', max_length=8),
        ),
        migrations.AlterField(
            model_name='sesionestudiante',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sesionestudiante',
            name='rbd',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sesionestudiante',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='textobiblioteca',
            name='tipo_textual',
            field=models.CharField(choices=[('cuento', 'Cuento de Autor'), ('cuento_folclorico', 'Cuento Folclórico / Popular'), ('fabula', 'Fábula'), ('leyenda', 'Leyenda'), ('mito', 'Mito'), ('poema', 'Poema'), ('soneto', 'Soneto'), ('oda', 'Oda'), ('noticia', 'Noticia'), ('reportaje', 'Reportaje'), ('articulo_info', 'Artículo Informativo'), ('articulo_cient', 'Artículo Científico (Divulgativo)'), ('infografia', 'Infografía'), ('instructivo', 'Instrucciones / Instructivo'), ('receta', 'Receta de Cocina'), ('manual', 'Manual de Instrucciones'), ('biografia', 'Biografía / Relato Histórico'), ('carta_formal', 'Carta Formal'), ('carta_director', 'Carta al Director'), ('carta_informal', 'Carta Informal'), ('afiche', 'Afiche Publicitario'), ('discontinuo', 'Texto Informativo Discontinuo')], max_length=20),
        ),
    ]
