# Generated by Django 6.0.2 on 2026-08-08 19:36

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simce', '0006_alter_sesionestudiante_options_prueba_organizacion_and_more'),
        ('users', '0010_alter_user_tenant'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='prueba',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='simcedocumento',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='textobiblioteca',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='sesionestudiante',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_simce', to='users.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='sesionestudiante',
            name='establecimiento',
            field=models.CharField(max_length=20, verbose_name='Establecimiento (declarado)'),
        ),
    ]
