# Generated by Django 6.0.2 on 2026-08-08 19:43

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_meetingbooking_organizacion_meetingroom_organizacion'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='meetingbooking',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='meetingroom',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
    ]
