# Generated by Django 6.0.2 on 2026-08-08 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('region', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('orden', models.PositiveSmallIntegerField()),
                ('es_terminal', models.BooleanField(default=False, verbose_name='Cierra el lead')),
            ],
            options={
                'ordering': ['target', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('activa', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Verticales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=150, verbose_name='Persona de contacto')),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('web', models.URLField(blank=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('rbd', models.CharField(blank=True, max_length=10, verbose_name='RBD')),
                ('origen', models.CharField(choices=[('manual', 'Carga manual'), ('directorio', 'Directorio público'), ('referido', 'Referido'), ('inbound', 'Llegó solo')], default='manual', max_length=12)),
                ('hash_dedupe', models.CharField(editable=False, max_length=40, unique=True)),
                ('score', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('notas', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('valor_estimado', models.PositiveIntegerField(blank=True, null=True, verbose_name='Valor estimado (CLP)')),
                ('ultimo_contacto', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='crm.etapa')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Correo'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('telefono', 'Teléfono'), ('presencial', 'Presencial')], default='whatsapp', max_length=12)),
                ('enviado', models.TextField(verbose_name='Mensaje enviado')),
                ('respuesta', models.TextField(blank=True)),
                ('respondio', models.BooleanField(default=False, verbose_name='¿Respondió?')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_crm', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='crm.lead')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('meta_leads_dia', models.PositiveSmallIntegerField(default=20)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='crm.ciudad')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='crm.vertical')),
            ],
            options={
                'ordering': ['vertical', 'ciudad'],
                'unique_together': {('vertical', 'ciudad')},
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='crm.target'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='crm.target'),
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together={('target', 'orden')},
        ),
    ]
