# Generated by Django 6.0.2 on 2026-08-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencia', '0002_initial'),
        ('users', '0007_consolidar_establecimientos_duplicados'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationform',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organizacion', verbose_name='Organización'),
        ),
    ]
