# Generated by Django 6.0.2 on 2026-08-08 19:43

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidencia', '0003_evaluationform_organizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='evaluationform',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='evidencedocument',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
    ]
