# Generated by Django 6.0.2 on 2026-08-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_red', '0003_calendarevent_deleted_at_calendarevent_deleted_by_and_more'),
        ('users', '0007_consolidar_establecimientos_duplicados'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('mineduc', 'Plazo MINEDUC'), ('supereduc', 'Superintendencia de Educación'), ('agencia', 'Agencia de Calidad'), ('congregacional', 'Congregacional'), ('interno', 'Interno EE'), ('cultural', 'Cultural'), ('deportivo', 'Deportivo')], default='interno', max_length=20, verbose_name='Tipo'),
        ),
    ]
