# Generated by Django 6.0.2 on 2026-08-08 19:43

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_red', '0004_calendarevent_organizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='calendarevent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('mineduc', 'Plazo MINEDUC'), ('supereduc', 'Superintendencia de Educación'), ('agencia', 'Agencia de Calidad'), ('organizacional', 'De la organización'), ('interno', 'Interno EE'), ('cultural', 'Cultural'), ('deportivo', 'Deportivo')], default='interno', max_length=20, verbose_name='Tipo'),
        ),
    ]
